### ISSUE TITLE
Proper way of serving AngularJS from a different public directory

### ISSUE THREAD

**Issue by lozadaOmr** [lozadaOmr/satellizer#1]
After following the instructions poste [here](mattstauffer.co/blog/upgrading-from-laravel-4-to-laravel-5)

I have encountered an error after changing the public_path of the Laravel app, instead of 
`examples/server/php/app/public` into `examples/client/`

It would seem that when AngularJS is serve from this new directory, it can't find the other scripts which results in the error:

`Unexpected Token <`

![satellizer-error](https://cloud.githubusercontent.com/assets/2493327/6884626/0b88ddb6-d62f-11e4-8168-7e89cefc9d22.png)

**Comment by lozadaOmr** [comment]
Using Apache2

change the  **DocumentRoot** to point to `examples/client` where index.html is located

**Comment by lagbox** [comment]
It looks like your relative urls are the problem.

**Comment by lozadaOmr** [comment]
@lagbox I tried moving the files into laravel's public directory and it found, I'm guessing that since I used File::get() on my HomeController. It is only looking at the client/index.html because. But after that it still considers looking at Laravel's public directory.

So I'm thinking that binding the public path is not permanent (previously on Laravel 4.2 only need to modify paths.php)

**Comment by lagbox** [comment]
Laravel doesn't serve files from it's public folder. The webserver handles those requests directly.

**Comment by lozadaOmr** [comment]
@lagbox looking at [sahat/satellizer](https://github.com/sahat/satellizer) I was hoping this could be migrated to use Laravel 5.0

From the example provide using Laravel 4.

 1. [Set parent client as public directory](https://github.com/sahat/satellizer/blob/master/examples/server/php/bootstrap/paths.php#L29)
 2. Add [route](https://github.com/sahat/satellizer/blob/master/examples/server/php/app/routes.php#L27) that will handle AngularJS
 3. Set controller to [return](https://github.com/sahat/satellizer/blob/master/examples/server/php/app/controllers/HomeController.php#L7) index.html

After basically it will work.

**Comment by lagbox** [comment]
Sorry ... updated previous comment

**Comment by lagbox** [comment]
Try this in your `HomeController`

```
public function index($angular = 'index.html')
{
    return \File::get(public_path().'/'. $angular);
}
```

**Comment by lozadaOmr** [comment]
@lagbox It sort-of worked, but I had to enter index.html it did load everything correctly.

Unfortunately if I click on links (Home, Login, Sign Up) it gives an Error 500

**Comment by lagbox** [comment]
This is a demo, you wouldn't actually set things up like this.

**Comment by lozadaOmr** [comment]
@lagbox Tried it, but the result was Error 500 if I enter '/' root directory on address bar. 

But it would load correctly only if I type in /index.html. After that if I click on link (Home, Login, Sign Up) will result in Error 500 also

**Comment by lozadaOmr** [comment]
@lagbox Yes I am aware it is a demo I was just trying to migrate the php example into Laravel 5.

**Comment by lagbox** [comment]
you did already

**Comment by lozadaOmr** [comment]
Laravel 5 can now be found in [examples/php](https://github.com/sahat/satellizer/tree/master/examples/server/php)

Resorted to just put  Satellizer inside **public** directory
